- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:

    - name: Provision instance
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"  
        ec2_region: "{{ AWS_REGION }}"
        instance_type: t2.micro
        keypair: jenkinsKP
        image: ami-098bb5d92c8886ca1 #RHEL 8
        assign_public_ip: yes
        vpc_subnet_id: subnet-0b3eb935
        group: mysecgp
        wait: true
        exact_count: 1
        count_tag: 
          Name: webserver
        instance_tags:
          Name: webserver
      register: ec2
    - debug:
        var: ec2
        
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 300
        state: started
      with_items: "{{ ec2.instances }}"
                
        
- hosts: tag_Name_webserver
  gather_facts: no
  become: yes
  remote_user: ec2-user
  tasks:
    - name: wait for SSH
      wait_for_connection:
        delay: 120
        timeout: 360
        
    - name: ping the server
      ping:
      
    - name: install nginx
      yum:
        name: nginx
        state: latest
        
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
        
        
        
